In [19]:
# ruff: noqa: F401

In [20]:
%load_ext autoreload
%load_ext pyinstrument
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
The pyinstrument extension is already loaded. To reload it, use:
  %reload_ext pyinstrument

In [39]:
import hvplot.polars

In [21]:
from datetime import datetime
from typing import Any

import numpy as np
import polars as pl

from encomp.coolprop import fluid, water
from encomp.fluids import Fluid, Water
from encomp.misc import isinstance_types
from encomp.units import Quantity as Q
from encomp.units import Unit
from encomp.utypes import (
    DT,
    MT,
    Currency,
    Density,
    Dimensionality,
    Dimensionless,
    Length,
    Mass,
    Numpy1DArray,
    Power,
    Temperature,
    TemperatureDifference,
    Time,
    UnitsContainer,
    UnknownDimensionality,
)

In [22]:
pl.select(water("D", pl.lit(21e5).alias("P"), pl.lit(300 + 273).alias("T")))

shape: (1, 1)
┌──────────┐
│ D        │
│ ---      │
│ f64      │
╞══════════╡
│ 8.393387 │
└──────────┘

In [23]:
pl.select(Fluid("IF97::Water", P=Q(pl.lit(25), "bar"), T=Q(pl.lit(25), "degC")).D.m)

shape: (1, 1)
┌────────────┐
│ D          │
│ ---        │
│ f64        │
╞════════════╡
│ 998.125426 │
└────────────┘

In [38]:
N = 10_000_000
M = 50

df = pl.DataFrame({"P": np.linspace(2, 20, N), "T": np.linspace(100, 200, N)}).cast(pl.Float32)

df = df.with_columns(
    (Water(P=Q(pl.col.P * (idx + 1) / M, "bar"), T=Q(pl.col.T, "degC")).D.m.alias(f"ret_{idx}")) for idx in range(M)
)

In [47]:
df

shape: (10_000_000, 52)
┌───────────┬────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ P         ┆ T          ┆ ret_0    ┆ ret_1    ┆ … ┆ ret_46    ┆ ret_47    ┆ ret_48    ┆ ret_49    │
│ ---       ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f32       ┆ f32        ┆ f32      ┆ f32      ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32       │
╞═══════════╪════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2.0       ┆ 100.0      ┆ 0.02324  ┆ 0.046507 ┆ … ┆ 958.39483 ┆ 958.39672 ┆ 958.39862 ┆ 958.40051 │
│           ┆            ┆          ┆          ┆   ┆ 6         ┆ 9         ┆ 1         ┆ 3         │
│ 2.000002  ┆ 100.000008 ┆ 0.02324  ┆ 0.046507 ┆ … ┆ 958.39483 ┆ 958.39672 ┆ 958.39862 ┆ 958.40051 │
│           ┆            ┆          ┆          ┆   ┆ 6         ┆ 9         ┆ 1         ┆ 3         │
│ 2.000004  ┆ 100.000023 ┆ 0.02324  ┆ 0.046507 ┆ … ┆ 958.39483 ┆ 958.39672 ┆ 958.39862 ┆ 958.40045 │
│           ┆            ┆          ┆          ┆   ┆ 6         ┆ 9         ┆ 1         ┆ 2         │
│ 2.000005  ┆ 100.000031 ┆ 0.02324  ┆ 0.046507 ┆ … ┆ 958.39483 ┆ 958.39672 ┆ 958.39862 ┆ 958.40045 │
│           ┆            ┆          ┆          ┆   ┆ 6         ┆ 9         ┆ 1         ┆ 2         │
│ 2.000007  ┆ 100.000038 ┆ 0.02324  ┆ 0.046507 ┆ … ┆ 958.39483 ┆ 958.39672 ┆ 958.39862 ┆ 958.40045 │
│           ┆            ┆          ┆          ┆   ┆ 6         ┆ 9         ┆ 1         ┆ 2         │
│ …         ┆ …          ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 19.999992 ┆ 199.999954 ┆ 0.183549 ┆ 0.367857 ┆ … ┆ 864.91589 ┆ 864.94641 ┆ 864.97692 ┆ 865.00738 │
│           ┆            ┆          ┆          ┆   ┆ 4         ┆ 1         ┆ 9         ┆ 5         │
│ 19.999994 ┆ 199.999969 ┆ 0.183549 ┆ 0.367857 ┆ … ┆ 864.91589 ┆ 864.94641 ┆ 864.97692 ┆ 865.00738 │
│           ┆            ┆          ┆          ┆   ┆ 4         ┆ 1         ┆ 9         ┆ 5         │
│ 19.999996 ┆ 199.999985 ┆ 0.183549 ┆ 0.367857 ┆ … ┆ 864.91589 ┆ 864.94641 ┆ 864.97692 ┆ 865.00738 │
│           ┆            ┆          ┆          ┆   ┆ 4         ┆ 1         ┆ 9         ┆ 5         │
│ 19.999998 ┆ 199.999985 ┆ 0.183549 ┆ 0.367857 ┆ … ┆ 864.91589 ┆ 864.94641 ┆ 864.97692 ┆ 865.00738 │
│           ┆            ┆          ┆          ┆   ┆ 4         ┆ 1         ┆ 9         ┆ 5         │
│ 20.0      ┆ 200.0      ┆ 0.183549 ┆ 0.367857 ┆ … ┆ 864.91589 ┆ 864.94635 ┆ 864.97686 ┆ 865.00732 │
│           ┆            ┆          ┆          ┆   ┆ 4         ┆           ┆ 8         ┆ 4         │
└───────────┴────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [16]:
N = 1_000_000

In [ ]:
%%pyinstrument

w = Water(P=Q(pl.lit(5), "bar"), T=Q(pl.col.T, "degC"))

pl.DataFrame({"T": np.linspace(100, 200, N)}).with_columns(w.D.m)

In [18]:
# %%pyinstrument

w = Water(
    T=Q(np.linspace(100, 200, N), "degC"),
    P=Q(5, "bar"),
)

w.D.m

array([958.54102553, 958.54095361, 958.54088169, ...,   2.35275592,
         2.35275536,   2.35275481], shape=(1000000,))

In [9]:
repr(Water(P=Q(pl.lit(5), "bar"), T=Q(50, "degC")))

'<Water (Unknown), P=<pl.Expr>, T=<pl.Expr>, D=<pl.Expr>, V=<pl.Expr>>'

In [10]:
pl.select(Water(P=Q(pl.lit(5), "bar"), T=Q(pl.lit(250), "degC")).D.m)

shape: (1, 1)
┌──────────┐
│ D        │
│ ---      │
│ f64      │
╞══════════╡
│ 2.107798 │
└──────────┘

In [11]:
pl.DataFrame({"T": [150, 200, 250]}).select((pl.col.T * 2).alias("asd"))

shape: (3, 1)
┌─────┐
│ asd │
│ --- │
│ i64 │
╞═════╡
│ 300 │
│ 400 │
│ 500 │
└─────┘